UjAnthologySSO.Web/Areas/Admin/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UjAnthologySSO.DataAccess;
using UjAnthologySSO.DataAccess.Repository.IRepository;
using UjAnthologySSO.Models;


namespace UjAnthologySSO.Web.Areas.Admin.Controllers
{
    public class CoursesController : Controller
    {
        private readonly IUnitOfWork _context;

        public CoursesController(IUnitOfWork context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            IEnumerable<Course> objCourses = _context.Courses.GetAll();
            return View(objCourses);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var course = _context.Courses.GetFirstOrDefault(x => x.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The display order cannot match the name of the course");
            }

            if (ModelState.IsValid)
            {
                _context.Courses.Add(obj);
                _context.Save();
                TempData["success"] = "Course has been created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var course = _context.Courses.GetFirstOrDefault(u => u.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Course obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The display order cannot match the name of the course");
            }

            if (ModelState.IsValid)
            {
                _context.Courses.Update(obj);
                _context.Save();
                TempData["success"] = "Course has been created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var course = _context.Courses.GetFirstOrDefault(x => x.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var course = _context.Courses.GetFirstOrDefault(x => x.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            _context.Courses.Remove(course);
            _context.Save();

            TempData["success"] = "Course has been deleted successfully";
            return RedirectToAction("Index");
        }



    }
}

UjAnthologySSO.Web/Areas/Admin/Controllers/CoverTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UjAnthologySSO.DataAccess;
using UjAnthologySSO.DataAccess.Repository.IRepository;
using UjAnthologySSO.Models;


namespace UjAnthologySSO.Web.Areas.Admin.Controllers
{
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _context;

        public CoverTypeController(IUnitOfWork context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            IEnumerable<CoverType> coverTypes = _context.CoverType.GetAll();
            return View(coverTypes);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var coverType = _context.CoverType.GetFirstOrDefault(x => x.Id == id);

            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CoverType obj)
        {
            

            if (ModelState.IsValid)
            {
                _context.CoverType.Add(obj);
                _context.Save();
                TempData["success"] = "Cover Type has been created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var coverType = _context.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CoverType obj)
        {
            

            if (ModelState.IsValid)
            {
                _context.CoverType.Update(obj);
                _context.Save();
                TempData["success"] = "Cover Type has been created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var coverType = _context.CoverType.GetFirstOrDefault(x => x.Id == id);

            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var coverType = _context.CoverType.GetFirstOrDefault(x => x.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            _context.CoverType.Remove(coverType);
            _context.Save();

            TempData["success"] = "Cover Type has been deleted successfully";
            return RedirectToAction("Index");
        }



    }
}

UjAnthologySSO.Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UjAnthologySSO.DataAccess;
using UjAnthologySSO.DataAccess.Repository.IRepository;
using UjAnthologySSO.Models;
using UjAnthologySSO.Models.ViewModels;


namespace UjAnthologySSO.Web.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _context;

        public ProductController(IUnitOfWork context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Product> products = _context.Product.GetAll();
            return View(products);
        }
      

      
        // GET: Product/Edit/5
        public async Task<IActionResult> Upsert(int? id)
        {
            ProductVM productVm = new()
            {
                product = new Product(),
                CourseList = _context.Courses.GetAll().Select(x =>
                    new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                CoverList = _context.CoverType.GetAll().Select(x =>
                    new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    })
            };

            if (id == null || id == 0)
            {
                //create a product
              
                return View(productVm);
            }
            else
            {
                // update a product
            }

            return View(productVm);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ProductVM obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //_context.CoverType.Update(obj);
                _context.Save();
                TempData["success"] = "Cover Type has been created successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

       



    }
}

UjAnthologySSO.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UjAnthologySSO.Web</title>
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*   <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/css/slicknav.css" />
    <link rel="stylesheet" href="~/css/flaticon.css" />
    <link rel="stylesheet" href="~/css/animate.min.css"/>
    <link rel="stylesheet" href="~/css/magnific-popup.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css" integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/slick.css" />
    <link rel="stylesheet" href="~/css/nice-select.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


@*    <link rel="stylesheet" href="~/UjAnthologySSO.Web.styles.css" asp-append-version="true" />*@
</head>
<body>
@*begin: Header Navbar*@
<div class="header-area">
    <div class="main-header header-sticky">
        <div class="container-fluid">
            <div class="menu-wrapper d-flex align-items-center justify-content-between">
                <div class="left-content d-flex align-items-center">
                    <div class="logo">
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="/img/UJ_Logo.png"
                                 style="width: 100%; height: 100px" alt=""/>
                        </a>
                    </div>
                    <!-- Search Box -->
                    <form action="#" class="form-box">
                        <input type="text"
                               name="Search"
                               placeholder="Search courses.."/>
                        <div class="search-icon">
                            <i class="ti-search"></i>
                        </div>
                    </form>
                </div>
                <!-- Main-menu -->
                <div class="main-menu d-none d-lg-block">
                    <nav>
                        <ul id="navigation">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">About</a></li>
                            
                            
                            <li>
                                <a href="#">Admin</a>
                                <ul class="submenu">
                                    <li><a asp-area="Admin"  asp-controller="Courses" asp-action="Index">Browse Courses</a></li>
                                    <li><a asp-area="Admin" asp-controller="CoverType" asp-action="Index">Covers</a></li>
                                    <li><a asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a></li>

                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Blog Details</a></li>
                                    <li><a href="#">Element</a></li>
                                </ul>
                            </li>
                            <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="SignIn" class="btn header-btn2">Sign In</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- Mobile Menu -->
            <div class="col-12">
                <div class="mobile_menu d-block d-lg-none"></div>
            </div>
        </div>
    </div>
</div>
@*end: Header Navbar*@
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()<!-- Scroll Up -->

    </main>
  
</div>
@*Begin Footer*@
    <footer>
        <div class="footer-area footer-padding">
            <div class="footer-wrapper">
                <div class="container">
                    <div class="row d-flex justify-content-between">
                        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="single-footer-caption mb-30">
                                    <!-- logo -->
                                    <div class="footer-logo mb-25">
                                        <a href="index.html">
                                            <img src="assets/img/logo/uj_logo.gif"
                                                 style="width: 100%; height: 50px"
                                                 alt="" />
                                        </a>
                                    </div>
                                    <div class="footer-tittle">
                                        <div class="footer-pera">
                                            <p>
                                                The automated process starts as soon as your clothes
                                                go into the machine.
                                            </p>
                                        </div>
                                    </div>
                                    <!-- social -->
                                    <div class="footer-social">
                                        <a href="#"><i class="fab fa-twitter"></i></a>
                                        <a href="https://bit.ly/sai4ull">
                                            <i class="fab fa-facebook-f"></i>
                                        </a>
                                        <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-4 col-sm-5">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Subjects</h4>
                                    <ul>
                                        <li><a href="#">Design & creatives</a></li>
                                        <li><a href="#">Telecommunication</a></li>
                                        <li><a href="#">Restaurant</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- footer-bottom area -->
                <div class="footer-bottom-area">
                    <div class="container">
                        <div class="footer-border">
                            <div class="row d-flex align-items-center">
                                <div class="col-xl-12">
                                    <div class="footer-copy-right text-center">
                                        <p>
                                            Copyright &copy;
                                            <script>
                                                document.write(new Date().getFullYear());
                                            </script>
                                            All rights reserved |
                                            <a href="https://uj.ac.za"
                                               target="_blank"
                                               rel="nofollow noopener">University Of Johannesburg</a>
                                            |
                                            <a asp-controller="Home" asp-action="Privacy"
                                              >Terms &amp; Conditions</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
@*End Footer*@
@*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
@*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
@*<script src="~/js/site.js" asp-append-version="true"></script>*@
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
<script src="~/js/vendor/jquery-1.12.4.min.js"></script>
<script src="~/js/owl.carousel.min.js"></script>
<script src="~/js/slick.min.js"></script>
<script src="~/js/jquery.slicknav.min.js"></script>
<script src="~/js/wow.min.js"></script>
<script src="~/js/jquery.nice-select.min.js"></script>
<script src="~/js/jquery.counterup.min.js"></script>
<script src="~/js/waypoints.min.js"></script>
<script src="~/js/plugins.js"></script>
<script src="~/js/main.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>











@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UjAnthologySSO.Web/Views/Shared/_Notification.cshtml
@if(TempData["success"]!= null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
    toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        toastr.error('@TempData["error"]')
    </script>
}